### ISSUE TITLE
Escolha do aplicativo para o projeto

### ISSUE THREAD

**Issue by ZenildaVieira** [Requisitos-de-Software/2023.2-Grupo01#2]
# Escolha do aplicativo para o projeto
# Descrição
Nesta issue, cada membro do grupo vai pesquisar um aplicativo que será candidato a ser utilizado no trabalho da disciplina de Requisitos de Software. Em seguida, decidiremos, em grupo, qual deles é o mais adequado para o projeto.

# Atividades 

- [x] Realizar pesquisa e escolher o aplicativo _(Gabriel Rosa)_
- [x] Realizar pesquisa e escolher o aplicativo _(Gabriel Zaranza)_
- [x] Realizar pesquisa e escolher o aplicativo _(Izabella Alves)_
- [x] Realizar pesquisa e escolher o aplicativo _(Lucas de Oliveira)_
- [x] Realizar pesquisa e escolher o aplicativo _(Lucas Ribeiro)_
- [x] Realizar pesquisa e escolher o aplicativo _(Lucas Victor)_
- [x] Realizar pesquisa e escolher o aplicativo _(Zenilda Pedrosa)_

**Comment by LucasOliveiraDiasMarquesFerreira** [comment]
O aplicativo que eu escolhi é o do BB( Banco do Brasil), ele é um aplicativo com um design que parece que parou no tempo, não é muito intuitivo e eu diria que é básico até demais, como usuário frequente dele posso afirmar que ele é bem ruim e esteticamente muito desagradável, uma interface realmente mal projetada.

**Comment by GZaranza** [comment]
Eu escolhi o app do conecteSUS, muito usado durante a pandemia de Covid-19. Nele é possível ver cartão de vacinas, exames realizados, fazer controle de medicamentos receitados além de fornecer informações sobre o SUS.

**Comment by ZenildaVieira** [comment]
O aplicativo que eu escolhi foi o e-Título. Ele apresenta informações sobre título de eleitor e afins.

**Comment by lucassouzs** [comment]
O aplicativo escolhido por mim, foi o Signal, O Signal é um aplicativo de mensagens com foco em privacidade disponível para Android e iPhone (iOS). A plataforma é considerada “ultrassegura” por não armazenar informações de usuários ou ainda quaisquer dados que possam ser usados para identificá-los, além de ser baseada em código aberto - o que significa que qualquer pessoa pode replicar a sua segurança a outras plataformas. O número de usuários ativos da plataforma ultrapassou a marca de 40 milhões recentemente.

**Comment by gabrielrosa09** [comment]
O aplicativo por mim é o [Calibre E-book Management](https://calibre-ebook.com/). Ele é um gerenciador de eBooks de código aberto que ajuda a organizar e converter eBooks em diferentes formatos. O motivo da escolha é que o app dele é bem melhor que o próprio site, ele disponibilizar várias funcionalidades que o próprio site não tem.

**Comment by Lucas13032003** [comment]
O aplicativo escolhido por mim, foi CNH DIGITAL. Ele é uma versão eletrônica da carteira de motorista. Ela fica em um aplicativo no seu smartphone e tem a mesma validade da versão impressa. É conveniente e elimina a necessidade de carregar documentos físicos. Baixe o aplicativo oficial, cadastre-se e autentique-se para usá-lo. Verifique as regras locais sobre funcionalidades adicionais e aceitação internacional.
